log:
  level: INFO

server:
  host: localhost
  port: 8080

loki:
  endpoint: 'https://loki.example.com'

grafana:
    endpoint: 'https://grafana.example.com'

prune:
  dry: true
  namespaces:
    - default
  interval: '10m'
  ignored_users:
    - 'some-admin'
    - 'a-service-account'
  period: '1440h'
  labels:
    app: 'grafana'
    env: 'production'
  lower_threshold: 10
