name: Push

on:
  # Run on all pushes except tag pushes.
  # See https://github.com/orgs/community/discussions/25615#discussioncomment-3248483.
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  publish:
    name: Publish
    needs: [test, lint]
    uses: ./.github/workflows/publish.yml
    with:
      version: ${{ github.sha }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
