name: Tag

on:
  push:
    tags:
      - '*'

jobs:
  validate:
    name: Validate
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    outputs:
      is_semver: ${{ steps.check.outputs.is_semver }}
    steps:
      - name: Check if tag is semver
        id: check
        run: |
          if [[ "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_semver=true" >> $GITHUB_OUTPUT
          else
            echo "is_semver=false" >> $GITHUB_OUTPUT
          fi
  publish:
    name: Publish
    needs: validate
    if: needs.validate.outputs.is_semver == 'true'
    uses: ./.github/workflows/publish.yml
    with:
      version: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
